/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-09-29 17:02:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Course_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./ExtCss.css\">\r\n");
      out.write("        <script src=\"./script.js\"></script>     \r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("    \r\n");
      out.write("    	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-3\">\r\n");
      out.write("					<label class=\"font\">VCUBE</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-6\">\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-3\">\r\n");
      out.write("			\r\n");
      out.write("				<h1 class=\"font1\">Welcome ");
      out.print( session.getAttribute("username") );
      out.write("</h1>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-2\"></div>\r\n");
      out.write("                <div class=\"col-sm-8 top\">\r\n");
      out.write("                    <h4>COURSES</h4>\r\n");
      out.write("                    <form class=\"form-group\"  name=\"login\" method=\"post\" action=\"course\"  onsubmit=\"return error()\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <input  class=\"form-control\" type=\"text\" name=\"course\" id=\"course\" placeholder=\"*COURSE NAME\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" name=\"fee\" id=\"fee\" placeholder=\"*FEES\" required>\r\n");
      out.write("                                <p></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                               \r\n");
      out.write("                                <select class=\"form-control\" id=\"duration\" name=\"duration\" required>\r\n");
      out.write("                                    <option value=\"\"selected>COURSE-DURATION (IN MONTHS)</option>\r\n");
      out.write("                                    <option value=\"1\">1</option>\r\n");
      out.write("                                    <option value=\"2\">2</option>\r\n");
      out.write("                                    <option value=\"3\">3</option>\r\n");
      out.write("                                    <option value=\"4\">4</option>\r\n");
      out.write("                                    <option value=\"5\">5</option>\r\n");
      out.write("                                    <option value=\"6\">6</option>\r\n");
      out.write("                                    <option value=\"7\">7</option>\r\n");
      out.write("                                    <option value=\"8\">8</option>\r\n");
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-6\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" name=\"location\" id=\"location\" placeholder=\"*LOCATION\" required>\r\n");
      out.write("                                <p></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-12\">\r\n");
      out.write("                                    <button  type=\"submit\" class=\" form-control btn btn-success\">LOGIN</button>\r\n");
      out.write("                                    <p id=\"p1\"> </p>                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-2\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            document.getElementById(\"course\").addEventListener(\"keypress\",func1);\r\n");
      out.write("            document.getElementById(\"fee\").addEventListener(\"keypress\",func2);\r\n");
      out.write("            function func1(event){\r\n");
      out.write("                var chh=event.which\r\n");
      out.write("                if(!((chh>=65 && chh<=90) || (chh>=97 && chh<=122)||(chh==32))){\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            function func2(event){\r\n");
      out.write("                var ch=event.which;\r\n");
      out.write("                if(!((ch>=48 &&ch<=57))){\r\n");
      out.write("                    event.preventDefault();\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            function error(){\r\n");
      out.write("\r\n");
      out.write("                var course=document.getElementById(\"course\").value;\r\n");
      out.write("                var fee=document.getElementById(\"fee\").value;\r\n");
      out.write("                var duration=document.getElementById(\"duration\").value;\r\n");
      out.write("                var location=document.getElementById(\"location\").value;\r\n");
      out.write("                \r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                if(course==\"\"||fee==\"\"||duration==\"\"||location==\"\"){\r\n");
      out.write("\r\n");
      out.write("                    document.getElementById(\"p1\").innerHTML=\"*ENTER ALL MANDATORY FIELDS\";\r\n");
      out.write("                    document.getElementById(\"p1\").style.color=\"red\";\r\n");
      out.write("\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("                else{\r\n");
      out.write("                    return true;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
