/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-10-02 03:47:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import modal.FacultyModal;
import java.util.List;

public final class FacultyUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("modal.FacultyModal");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	List<FacultyModal> facultyobj = (List<FacultyModal>) session.getAttribute("facultylistid");
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	System.out.println("enterd faculty update jsp");
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-sm-2\"></div>\r\n");
      out.write("			<div class=\"col-sm-8 top\">\r\n");
      out.write("\r\n");
      out.write("				");

				for (FacultyModal fm : facultyobj) {
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<h4>FACULTY REGISTRATION</h4>\r\n");
      out.write("				<form class=\"form-group\" method=\"post\"\r\n");
      out.write("					action=\"facultyupdate2controller\" name=\"faculty\"\r\n");
      out.write("					onsubmit=\"return error()\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" type=\"text\" id=\"id\" name=\"id\"\r\n");
      out.write("								placeholder=\"*ID\" readonly value=");
      out.print(fm.getId());
      out.write(">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" type=\"text\" id=\"first_name\"\r\n");
      out.write("								name=\"firstname\" placeholder=\"*FIRST NAME\"\r\n");
      out.write("								value=");
      out.print(fm.getFirstname());
      out.write(">\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<select class=\"form-control\" id=\"gender\" name=\"gender\"\r\n");
      out.write("								value=");
      out.print(fm.getGender());
      out.write(">\r\n");
      out.write("								<option value=\"\" selected>GENDER</option>\r\n");
      out.write("								<option value=\"male\">MALE</option>\r\n");
      out.write("								<option value=\"female\">FEMALE</option>\r\n");
      out.write("								<option value=\"others\">OTHERS</option>\r\n");
      out.write("							</select>\r\n");
      out.write("							<p></p>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" onfocus=\"firstlast1()\"\r\n");
      out.write("								onblur=\"firstlast()\" type=\"text\" id=\"last_name\" name=\"lastname\"\r\n");
      out.write("								placeholder=\"*LAST NAME\" value=");
      out.print(fm.getLastname());
      out.write(">\r\n");
      out.write("							<p id=\"fila\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" type=\"text\" id=\"mobile\"\r\n");
      out.write("								maxlength=\"10\" name=\"mobile\" placeholder=\"*MOBILE\" readonly\r\n");
      out.write("								value=");
      out.print(fm.getMobile());
      out.write(">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" type=\"text\" id=\"gmail\" name=\"mail\"\r\n");
      out.write("								placeholder=\"*MAIL ID\" value=");
      out.print(fm.getMail());
      out.write(">\r\n");
      out.write("							<p></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("							<input class=\"form-control\" type=\"text\" id=\"year\" name=\"year\"\r\n");
      out.write("								placeholder=\"*YEARS OF EXPERIENCE\" value=");
      out.print(fm.getYear());
      out.write(">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("							<select class=\"form-control\" id=\"course\" name=\"course\"\r\n");
      out.write("								value=");
      out.print(fm.getCourse());
      out.write(">\r\n");
      out.write("								<option value=\"\" selected>COURSES</option>\r\n");
      out.write("								<option value=\"java\">JAVA</option>\r\n");
      out.write("								<option value=\"python\">PYTHON</option>\r\n");
      out.write("								<option value=\"dot net\">DOT NET</option>\r\n");
      out.write("								<option value=\"aws\">AWS</option>\r\n");
      out.write("								<option value=\"salesforce\">SALESFORCE</option>\r\n");
      out.write("							</select>\r\n");
      out.write("							<p></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-12\">\r\n");
      out.write("							<button type=\"submit\" class=\" form-control btn btn-success\">SUBMIT</button>\r\n");
      out.write("							<p id=\"p1\"></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-sm-2\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"./script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		document.getElementById(\"first_name\").addEventListener(\"keypress\",\r\n");
      out.write("				func1);\r\n");
      out.write("		document.getElementById(\"last_name\")\r\n");
      out.write("				.addEventListener(\"keypress\", func1);\r\n");
      out.write("		document.getElementById(\"mobile\").addEventListener(\"keypress\", func2);\r\n");
      out.write("		document.getElementById(\"year\").addEventListener(\"keypress\", func2);\r\n");
      out.write("\r\n");
      out.write("		function func1(event) {\r\n");
      out.write("			var chh = event.which\r\n");
      out.write("			if (!((chh >= 65 && chh <= 90) || (chh >= 97 && chh <= 122) || (chh == 32))) {\r\n");
      out.write("				event.preventDefault();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function func2(event) {\r\n");
      out.write("			var ch = event.which;\r\n");
      out.write("			if (!((ch >= 48 && ch <= 57))) {\r\n");
      out.write("				event.preventDefault();\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function verify1() {\r\n");
      out.write("\r\n");
      out.write("			document.getElementById(\"repswd\").innerHTML = \"\";\r\n");
      out.write("		}\r\n");
      out.write("		function verify() {\r\n");
      out.write("			var pswd = document.getElementById(\"password\").value;\r\n");
      out.write("			var repswd = document.getElementById(\"confirmpassword\").value;\r\n");
      out.write("\r\n");
      out.write("			if (pswd == repswd) {\r\n");
      out.write("				document.getElementById(\"repswd\").innerHTML = \"\";\r\n");
      out.write("			} else {\r\n");
      out.write("\r\n");
      out.write("				document.getElementById(\"repswd\").innerHTML = \"Confirm Password Mis-Matched\";\r\n");
      out.write("				document.getElementById(\"repswd\").style.color = \"red\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function firstlast() {\r\n");
      out.write("\r\n");
      out.write("			var first_name = document.getElementById(\"first_name\").value;\r\n");
      out.write("			var last_name = document.getElementById(\"last_name\").value;\r\n");
      out.write("			if (first_name == last_name) {\r\n");
      out.write("				document.getElementById(\"fila\").innerHTML = \"*FIRST AND LAST NAME SHOULD BE DIFFERENT\";\r\n");
      out.write("				document.getElementById(\"fila\").style.color = \"red\";\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function firstlast1() {\r\n");
      out.write("			document.getElementById(\"fila\").innerHTML = \"\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function error() {\r\n");
      out.write("			var first_name = document.getElementById(\"first_name\").value;\r\n");
      out.write("			var last_name = document.getElementById(\"last_name\").value;\r\n");
      out.write("			var mobile = document.getElementById(\"mobile\").value;\r\n");
      out.write("			var gmail = document.getElementById(\"gmail\").value;\r\n");
      out.write("			var year = document.getElementById(\"year\").value;\r\n");
      out.write("			var course = document.getElementById(\"course\").value;\r\n");
      out.write("			var gender=document.getElementById(\"gender\").value;\r\n");
      out.write("\r\n");
      out.write("			if (first_name == \"\" || last_name == \"\" || mobile == \"\"\r\n");
      out.write("					|| gmail == \"\" || year == \"\" || course == \"\"||gender==\"\") {\r\n");
      out.write("\r\n");
      out.write("				document.getElementById(\"p1\").innerHTML = \"*ENTER ALL MANDATORY FIELDS\";\r\n");
      out.write("				document.getElementById(\"p1\").style.color = \"red\";\r\n");
      out.write("\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			else if (first_name == last_name) {\r\n");
      out.write("				document.getElementById(\"fila\").innerHTML = \"*FIRST AND LAST NAME SHOULD BE DIFFERENT\";\r\n");
      out.write("				document.getElementById(\"fila\").style.color = \"red\";\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (!(pswd == repswd)) {\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			else {\r\n");
      out.write("				return true;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
